name: Build Check and Push images
on:
  push:
    branches:
      - main
    paths:
      - 'iits-images/*/build-info.json'

jobs:

  get-changed-images:
    name: Find changed images
    runs-on: ubuntu-latest
    outputs:
      matrix: "${{ steps.get_changed_images_folders.outputs.matrix }}"
    steps:
      - uses: actions/checkout@v1
      - name: Get changed images
        id: get_changed_images
        uses: tj-actions/changed-files@v35.9.1
        with:
          json: true
          files: |
            ./iits-images/**
          dir_names: true
          dir_names_exclude_root: true
          dir_names_max_depth: 2

      - name: Echo changed files
        id: get_changed_images_folders
        run: echo matrix=${{ steps.get_changed_images.outputs.all_changed_files }} >> $GITHUB_OUTPUT

  build-check-push:
    uses: ./.github/workflows/helper_build_check_push_sign_image.yml
    name: Build Check & Push changed images
    needs: get-changed-images
    if: ${{ needs.get-changed-images.outputs.matrix != '' && toJson(fromJson(needs.get-changed-images.outputs.matrix)) != '[]' }}
    strategy:
      matrix:
        chart: ${{fromJSON(needs.get-changed-images.outputs.matrix)}}
    with:
      target-directory: "${{ matrix.chart }}"
    secrets:
      GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}